/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "on-surface-variant": "#464555",
        "on-secondary-fixed-variant": "#3c475a",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "tertiary-container": "#a44100",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb695",
        "on-secondary-container": "#586377",
        "on-primary-container": "#dad7ff",
        "tertiary": "#7e3000",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "surface": "#f7f9fb",
        "tertiary-fixed": "#ffdbcc",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#111c2d",
        "primary-fixed-dim": "#c3c0ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#d8e3fb",
        "primary-fixed": "#e2dfff",
        "surface-container": "#eceef0",
        "on-tertiary": "#ffffff",
        "secondary": "#545f73",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#351000",
        "outline": "#777587",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "primary-container": "#4f46e5",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#4d44e3",
        "primary": "#3525cd",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#d5e0f8",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-primary": "#c3c0ff",
        "background": "#f7f9fb",
        "on-tertiary-container": "#ffd2be",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "sidebar-width": "240px",
        "container-max": "1600px",
        "section-gap": "24px",
        "margin-desktop": "32px",
        "stack-compact": "4px",
        "gutter": "16px",
        "stack-default": "12px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "mono-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
