--
-- PostgreSQL database dump
--

\restrict PiQlBptRJBcFxbdFgQaJDKyYNAsM1LgsVV4ADXHpy11lDLHJUOeke35Dl7r6TVc

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: application_dependencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.application_dependencies (
    id integer NOT NULL,
    source_app_id integer,
    dependent_app_id integer,
    dependency_nature character varying(20)
);


ALTER TABLE public.application_dependencies OWNER TO postgres;

--
-- Name: application_dependencies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.application_dependencies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.application_dependencies_id_seq OWNER TO postgres;

--
-- Name: application_dependencies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.application_dependencies_id_seq OWNED BY public.application_dependencies.id;


--
-- Name: application_purposes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.application_purposes (
    id integer NOT NULL,
    application_id integer,
    purpose_text text NOT NULL,
    embedding public.vector(768)
);


ALTER TABLE public.application_purposes OWNER TO postgres;

--
-- Name: application_purposes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.application_purposes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_purposes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_symptoms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.application_symptoms (
    id integer NOT NULL,
    application_id integer NOT NULL,
    symptom_text text NOT NULL,
    embedding public.vector(768)
);


ALTER TABLE public.application_symptoms OWNER TO postgres;

--
-- Name: application_symptoms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.application_symptoms_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.application_symptoms_id_seq OWNER TO postgres;

--
-- Name: application_symptoms_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.application_symptoms_id_seq OWNED BY public.application_symptoms.id;


--
-- Name: applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.applications (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    owning_team character varying(100),
    contact character varying(200)
);


ALTER TABLE public.applications OWNER TO postgres;

--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.applications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.applications_id_seq OWNER TO postgres;

--
-- Name: applications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.applications_id_seq OWNED BY public.applications.id;


--
-- Name: intakes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.intakes (
    id integer NOT NULL,
    raw_text text NOT NULL,
    operator_id character varying(50),
    created_at timestamp without time zone DEFAULT now(),
    complainant_service_no character varying(20),
    complainant_name character varying(100),
    complainant_unit character varying(100),
    complainant_rank character varying(50)
);


ALTER TABLE public.intakes OWNER TO postgres;

--
-- Name: intakes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.intakes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.intakes_id_seq OWNER TO postgres;

--
-- Name: intakes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.intakes_id_seq OWNED BY public.intakes.id;


--
-- Name: learning_examples; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_examples (
    id integer NOT NULL,
    ticket_number character varying(20),
    raw_text text NOT NULL,
    text_embedding public.vector(768),
    predicted_app_id integer,
    confirmed_app_id integer
);


ALTER TABLE public.learning_examples OWNER TO postgres;

--
-- Name: learning_examples_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.learning_examples_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.learning_examples_id_seq OWNER TO postgres;

--
-- Name: learning_examples_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.learning_examples_id_seq OWNED BY public.learning_examples.id;


--
-- Name: ticket_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_history (
    id integer NOT NULL,
    ticket_number character varying(20),
    changed_by character varying(50),
    old_status character varying(20),
    new_status character varying(20),
    notes text,
    changed_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.ticket_history OWNER TO postgres;

--
-- Name: ticket_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ticket_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ticket_history_id_seq OWNER TO postgres;

--
-- Name: ticket_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ticket_history_id_seq OWNED BY public.ticket_history.id;


--
-- Name: ticket_related_apps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_related_apps (
    ticket_number character varying(20) NOT NULL,
    related_application_id integer NOT NULL
);


ALTER TABLE public.ticket_related_apps OWNER TO postgres;

--
-- Name: tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tickets (
    ticket_number character varying(20) NOT NULL,
    intake_id integer,
    complainant_id character varying(50),
    primary_application_id integer,
    status character varying(20) DEFAULT 'open'::character varying,
    fault_type character varying(50),
    severity character varying(20) DEFAULT 'medium'::character varying,
    complainant_service_no character varying(20),
    complainant_rank character varying(50),
    complainant_unit character varying(100),
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.tickets OWNER TO postgres;

--
-- Name: application_dependencies id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_dependencies ALTER COLUMN id SET DEFAULT nextval('public.application_dependencies_id_seq'::regclass);


--
-- Name: application_symptoms id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_symptoms ALTER COLUMN id SET DEFAULT nextval('public.application_symptoms_id_seq'::regclass);


--
-- Name: applications id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications ALTER COLUMN id SET DEFAULT nextval('public.applications_id_seq'::regclass);


--
-- Name: intakes id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.intakes ALTER COLUMN id SET DEFAULT nextval('public.intakes_id_seq'::regclass);


--
-- Name: learning_examples id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_examples ALTER COLUMN id SET DEFAULT nextval('public.learning_examples_id_seq'::regclass);


--
-- Name: ticket_history id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_history ALTER COLUMN id SET DEFAULT nextval('public.ticket_history_id_seq'::regclass);


--
-- Name: application_dependencies application_dependencies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_dependencies
    ADD CONSTRAINT application_dependencies_pkey PRIMARY KEY (id);


--
-- Name: application_purposes application_purposes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_purposes
    ADD CONSTRAINT application_purposes_pkey PRIMARY KEY (id);


--
-- Name: application_symptoms application_symptoms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_symptoms
    ADD CONSTRAINT application_symptoms_pkey PRIMARY KEY (id);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: intakes intakes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT intakes_pkey PRIMARY KEY (id);


--
-- Name: learning_examples learning_examples_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_examples
    ADD CONSTRAINT learning_examples_pkey PRIMARY KEY (id);


--
-- Name: ticket_history ticket_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT ticket_history_pkey PRIMARY KEY (id);


--
-- Name: ticket_related_apps ticket_related_apps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_related_apps
    ADD CONSTRAINT ticket_related_apps_pkey PRIMARY KEY (ticket_number, related_application_id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (ticket_number);


--
-- Name: application_dependencies application_dependencies_dependent_app_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_dependencies
    ADD CONSTRAINT application_dependencies_dependent_app_id_fkey FOREIGN KEY (dependent_app_id) REFERENCES public.applications(id);


--
-- Name: application_dependencies application_dependencies_source_app_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_dependencies
    ADD CONSTRAINT application_dependencies_source_app_id_fkey FOREIGN KEY (source_app_id) REFERENCES public.applications(id);


--
-- Name: application_purposes application_purposes_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_purposes
    ADD CONSTRAINT application_purposes_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: application_symptoms application_symptoms_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_symptoms
    ADD CONSTRAINT application_symptoms_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: learning_examples learning_examples_confirmed_app_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_examples
    ADD CONSTRAINT learning_examples_confirmed_app_id_fkey FOREIGN KEY (confirmed_app_id) REFERENCES public.applications(id);


--
-- Name: learning_examples learning_examples_predicted_app_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_examples
    ADD CONSTRAINT learning_examples_predicted_app_id_fkey FOREIGN KEY (predicted_app_id) REFERENCES public.applications(id);


--
-- Name: learning_examples learning_examples_ticket_number_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_examples
    ADD CONSTRAINT learning_examples_ticket_number_fkey FOREIGN KEY (ticket_number) REFERENCES public.tickets(ticket_number);


--
-- Name: ticket_history ticket_history_ticket_number_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT ticket_history_ticket_number_fkey FOREIGN KEY (ticket_number) REFERENCES public.tickets(ticket_number);


--
-- Name: ticket_related_apps ticket_related_apps_related_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_related_apps
    ADD CONSTRAINT ticket_related_apps_related_application_id_fkey FOREIGN KEY (related_application_id) REFERENCES public.applications(id);


--
-- Name: ticket_related_apps ticket_related_apps_ticket_number_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_related_apps
    ADD CONSTRAINT ticket_related_apps_ticket_number_fkey FOREIGN KEY (ticket_number) REFERENCES public.tickets(ticket_number);


--
-- Name: tickets tickets_intake_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_intake_id_fkey FOREIGN KEY (intake_id) REFERENCES public.intakes(id);


--
-- Name: tickets tickets_primary_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_primary_application_id_fkey FOREIGN KEY (primary_application_id) REFERENCES public.applications(id);


--
-- PostgreSQL database dump complete
--

\unrestrict PiQlBptRJBcFxbdFgQaJDKyYNAsM1LgsVV4ADXHpy11lDLHJUOeke35Dl7r6TVc

